unit IntrashipServicesConst;

{$mode delphi}{$H+}

interface

const
  MAJOR_RELEASE = '1';
  MINOR_RELEASE = '0';
  DD_PROD_CODE = 'EPN';
  //EKP = '5000000008';
  EKP = '5000000000';
  PARTNER_ID = '01';

  SHIPMENT_DESC = 'Interessanter Artikel';
  SHIPPER_COMPANY_NAME = 'Deutsche Post IT Brief GmbH';
  SHIPPER_STREET = 'Heinrich-Bruening-Str.';
  SHIPPER_STREETNR = '7';
  SHIPPER_CITY = 'Bonn';
  SHIPPER_ZIP = '53113';
  SHIPPER_COUNTRY_CODE = 'DE';
  SHIPPER_CONTACT_EMAIL = 'max@muster.de';
  SHIPPER_CONTACT_NAME = 'Max Muster';
  SHIPPER_CONTACT_PHONE = '030244547777778';

  RECEIVER_FIRST_NAME = 'Kai';
  RECEIVER_LAST_NAME = 'Wahn';
  RECEIVER_LOCAL_STREET = 'Marktplatz';
  RECEIVER_LOCAL_STREETNR = '1';
  RECEIVER_LOCAL_CITY = 'Stuttgart';
  RECEIVER_LOCAL_ZIP = '70173';
  RECEIVER_LOCAL_COUNTRY_CODE = 'DE'; // Nicht verändern!!!

  RECEIVER_CONTACT_EMAIL = 'kai@wahn.de';
  RECEIVER_CONTACT_NAME = 'Kai Wahn';
  RECEIVER_CONTACT_PHONE = '+886 2 27781-8';
  RECEIVER_COMPANY_NAME = 'Klammer Company';
  DUMMY_SHIPMENT_NUMBER = '0000000';

  RECEIVER_WWIDE_STREET = 'Chung Hsiao East Road.';
  RECEIVER_WWIDE_STREETNR = '55';
  RECEIVER_WWIDE_CITY = 'Taipeh';
  RECEIVER_WWIDE_ZIP = '100';
  RECEIVER_WWIDE_COUNTRY = 'Taiwan';
  RECEIVER_WWIDE_COUNTRY_CODE = 'TW';

  SHIPPER_BANK_ACCOUNTOWNER = '.';
  SHIPPER_BANK_ACCOUNTNUMBER = '.';
  SHIPPER_BANK_BANKCODE = '.';
  SHIPPER_BANK_BANKNAME = '.';
  SHIPPER_BANK_BIC = '.33XXXXX';
  SHIPPER_BANK_IBAN = 'DE85.11111111111111111';
  SHIPPER_BANK_NOTE = 'BLahblub';

  COD_CODAMOUNT = '100.99';
  COD_CODCURRENCE = 'EUR';

  PACKSTATION = 'PACKSTATION';
  POSTOFFICE = 'POSTFILIALE';

  POST_OFFICE_ZIP = '59494';
  POST_OFFICE_CITY = 'Soest';
  POST_OFFICE_NUMBER = '544';
  POSTNUMBER = EKP;
  RECEIVERNAME_FOR_POST_OFFICE = 'Max Mustermann';


implementation

end.

